---
- name: upgrade all current packages to latest versions
  package:
    state: latest
    name: '*'

#- name: remove unused packages
#  package:
#    state: absent
#    name:
#      - logwatch
#      - mosh
#      - powerline
#      - python34
#      - python34-libs
#      - python34-pip
#      - python34-setuptools
#      - ntp

- name: add target user
  user:
    name: "{{ target_user }}"
    comment: "{{ target_user_name }}"
    groups: wheel
    append: yes
    generate_ssh_key: yes
