---
- name: set up John's preferred Fedora Workstation configuration
  hosts: workstation
  become: yes

  roles:
    - system/base
    - system/fedora-workstation
    - apps/base-workstation
    - apps/bash
    #- apps/dunst
    - apps/git
    - apps/i3wm
    #- apps/minecraft
    #- apps/npm
    #- apps/powerline-go
    - apps/ssh
    #- apps/task
    #- apps/bugwarrior  # intentionally after taskwarrior role
    - apps/thunderbird
    #- apps/tmux
    - apps/vim
